    CREATE TABLE IF NOT EXISTS USERS (
      user_id SERIAL PRIMARY KEY NOT NULL UNIQUE,
      name CHARACTER VARYING(255) NOT NULL,
      password CHARACTER VARYING(255) NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    );

    CREATE TABLE IF NOT EXISTS URL_SHORTER (
      code VARCHAR(255) PRIMARY KEY NOT NULL UNIQUE,
      name CHARACTER VARYING(255) NOT NULL,
      url CHARACTER VARYING(255) NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      visits INT  DEFAULT 0,
      user_id INT,
      FOREIGN KEY (user_id) REFERENCES USERS (user_id) ON DELETE CASCADE
    );
