version: '3'

services:
  app:
    build: .
    ports:
      - "3006:3006"
    environment:
      - REDIS_URL=redis://redis:6379
      - PORT=3006
      - DOMAIN=127.0.0.1
      - DB_USER=postgres
      - DB_HOST=postgres
      - DB_NAME=hillel
      - DB_PASSWORD=root
      - DB_PORT=5432
    depends_on:
      - redis
      - postgres
    volumes:
      - app-data:/usr/src/app/data

  redis:
    image: redis
    command: redis-server --bind 0.0.0.0
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: hillel
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  app-data:
  redis-data:
  postgres-data: